# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Mark Fairweather
email: fairweather.m@gmail.com
description: Design / Front-End Development / UX / Milwaukee WI
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://markfairweather.com" # the base hostname & protocol for your site
github_username:  mfairweather

# Build settings
markdown: kramdown

sass:
  style: compressed
